# Generated by Django 5.2.8 on 2025-11-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_profile_user_reservation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
