# Generated by Django 5.2.8 on 2025-12-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_reservation_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='held_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
